
list_categories = [
    "Aides culinaires",
    "Barres chocolatées",
    "Barres de céréales",
    "Boissons lactées",
    "Boissons instantanées",
    "Bonbons gélifiés",
    "Chocolats",
    "Confitures de fraises",
    "Confiseries chocolatées",
    "Crèmes",
    "Crèmes glacées en pot",
    "Crêpes et galettes",
    "Eaux de sources",
    'Epicerie',
    "Escalopes de dinde",
    "Jambons secs",
    "Jus de fruits à base de concentré",
    "Laits demi-écrémés",
    "Légumes frais",
    "Nouilles",
    "Pains d'épices",
    "Pates-a-tartiner",
    "Pâtes de blé dur",
    "Pâtés végétaux",
    "Poissons",
    "Rillettes de poissons",
    "ravioli",
    "Sardines à l'huile",
    "Sauces pour pâtes",
    "Saumons fumés",
    "Veloutés de légumes",
    "Viandes",
    "Vins rouges",
    "Yaourts brassés",
]

